config/routes.rb
Rails.application.routes.draw do
  resources :revenues

  resources :costs

  resources :incomes

  resources :categories do
    resources :revenues, :costs
  end
  root 'categories#index'

end

app/models/income.rb
class Income < ActiveRecord::Base
belongs_to :category
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:amount)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<h1>Listing incomes</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.amount %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>