config/routes.rb
Rails.application.routes.draw do
  resources :revenues

  resources :costs

  resources :incomes

  resources :categories do
    resources :revenues, :costs
  end
  root 'categories#index'

end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
belongs_to :category
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  before_action :set_revenue, only: [:show, :edit, :update, :destroy]

  # GET /revenues
  # GET /revenues.json
  def index
    @revenues = Revenue.all
  end

  # GET /revenues/1
  # GET /revenues/1.json
  def show
  end

  # GET /revenues/new
  def new
    @revenue = Revenue.new
  end

  # GET /revenues/1/edit
  def edit
  end

  # POST /revenues
  # POST /revenues.json
  def create
    @category = Category.find(params[:category_id])
    @revenue = @category.revenues.create(revenue_params)

    respond_to do |format|
      if @revenue.save
        format.html { redirect_to @category, notice: 'Revenue was successfully created.' }
        format.json { render :show, status: :created, location: @revenue }
      else
        format.html { render :new }
        format.json { render json: @revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /revenues/1
  # PATCH/PUT /revenues/1.json
  def update
    respond_to do |format|
      if @revenue.update(revenue_params)
        format.html { redirect_to @revenue, notice: 'Revenue was successfully updated.' }
        format.json { render :show, status: :ok, location: @revenue }
      else
        format.html { render :edit }
        format.json { render json: @revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revenues/1
  # DELETE /revenues/1.json
  def destroy
    @revenue.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Revenue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revenue
      @revenue = Revenue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revenue_params
      params.require(:revenue).permit(:category_id, :name, :amount)
    end
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/views/revenues/_form.html.erb
<%= form_for(@revenue) do |f| %>
  <% if @revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revenue.errors.count, "error") %> prohibited this revenue from being saved:</h2>

      <ul>
      <% @revenue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revenues/edit.html.erb
<h1>Editing revenue</h1>

<%= render 'form' %>

<%= link_to 'Show', @revenue %> |
<%= link_to 'Back', revenues_path %>

app/views/revenues/index.html.erb
<h1>Listing revenues</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @revenues.each do |revenue| %>
      <tr>
        <td><%= revenue.category_id %></td>
        <td><%= revenue.name %></td>
        <td><%= revenue.amount %></td>
        <td><%= link_to 'Show', revenue %></td>
        <td><%= link_to 'Edit', edit_revenue_path(revenue) %></td>
        <td><%= link_to 'Destroy', revenue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Revenue', new_revenue_path %>

app/views/revenues/new.html.erb
<h1>New revenue</h1>

<%= render 'form' %>

<%= link_to 'Back', revenues_path %>

app/views/revenues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @revenue.category_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @revenue.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @revenue.amount %>
</p>

<%= link_to 'Edit', edit_revenue_path(@revenue) %> |
<%= link_to 'Back', revenues_path %>