config/routes.rb
Rails.application.routes.draw do
  resources :revenues

  resources :costs

  resources :incomes

  resources :categories do
    resources :revenues, :costs
  end
  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :revenues, dependent: :destroy
has_many :costs, dependent: :destroy
self.inheritance_column = nil

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @totalcost = Cost.where(:category_id => @category).sum(:amount)
    @totalrevenue = Revenue.where(:category_id => @category).sum(:amount)
    @balance = @totalrevenue - @totalcost
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :type)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-md-6 col-md-offset-3">
 <div class="well">
  <div class="field">
    <%= f.label :name %>: Month<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %>: Year<br>
    <%= f.text_field :type %>
  </div>
      <br />
  <div class="actions">
    <%= f.submit class:'btn btn-success' %>
  </div>
<% end %>
</div>
</div>

app/views/categories/budget.html.erb
<nav class="navbar navbar-inverse">
  <h1> Bugetting</h1>
</nav>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @category.type %>
</p>
<%= form_for([@category, Revenue.new]) do |f| %>
    <p><%= f.label :name, "New Revenue" %><br/>
      <%= f.text_field :name %> <br />
      <%= f.label :name, "Amount" %><br/>
      <%= f.text_field :amount %>
    </p>

    <p><%= f.submit "Add Income" %></p>
<% end %>
<%= form_for([@category, Cost.new]) do |c| %>
    <p><%= c.label :name, "New Cost" %><br/>
      <%= c.text_field :name %> <br />
      <%= c.label :name, "Amount" %><br/>
      <%= c.text_field :amount %>
    </p>

    <p><%= c.submit "Add Cost" %></p>
<% end %>
<br />

<table>
  <tbody>
  <div id="revenues">
    <% @category.revenues.each do |revenue| %>
        <%= div_for revenue do %>

            <tr>
              <td>
                <h3>Income</h3>
                <strong>Posted <%= time_ago_in_words(revenue.created_at) %></strong><br/>
                <%= h(revenue.name) %>
                <%= h(revenue.amount) %>
              </td>
            </tr>

        <% end %>
    <% end %>
  </div>

  <table>
    <tbody>
    <div id="cost">
      <% @category.costs.each do |cost| %>
          <%= div_for cost do %>

              <tr>
                <td>
                  <h3>Cost</h3>
                  <strong>Posted <%= time_ago_in_words(cost.created_at) %></strong><br/>
                  <%= h(cost.name) %>
                  <%= h(cost.amount) %>
                </td>
              </tr>

          <% end %>
      <% end %>
    </div>

    </tbody>
  </table>
</table>

<nav class="navbar navbar-default navbar-fixed-bottom" body="padding-bottom: 70px;"
>
  <div class="container">
    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Back', categories_path %>
    <%= link_to 'Home', categories_path, class:'btn btn-default' %>
  </div>
</nav>

app/views/categories/edit.html.erb
<nav class="navbar navbar-inverse">
  <h1 align="center" style="color: #BBBBBB; font-family: 'Bitstream Vera Sans'"> Bugeting</h1>
</nav>
<h3 style="font-family: 'cursive' "> Edit This Category</h3>
<%= render 'form' %>

<nav class="navbar navbar-inverse navbar-fixed-bottom" style="align-self: center"
>
  <div class="container">

    <p class="navbar-text">
      <%= link_to 'Show', @category, class: 'btn btn-primary', style: 'align: center' %>
      <%= link_to 'Back', categories_path, class: 'btn btn-primary', style: 'align: center' %>
      <%= link_to 'Home', categories_path, class: 'btn btn-primary', style: 'align: center' %></p>

  </div>
</nav>

app/views/categories/index.html.erb
<nav class="navbar navbar-inverse">
  <h1 align="center" style="color: #BBBBBB; font-family: 'Bitstream Vera Sans'">Budgetting</h1>

</nav>

<h4 style="font-family: 'cursive' ">Track your income, and costs by month!</h4>
<table class="table table-bordered table-hover table-responsive table">
  <thead style="align-self: center">
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.type %></td>
        <td><%= link_to 'Show', category, class:'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class:'btn btn-default' %></td>
        <td><%= link_to 'Destroy', category, class:'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<nav class="navbar navbar-inverse navbar-fixed-bottom" style="align-self: center"
>
  <div class="container">

    <p class="navbar-text">
      <%= link_to 'New Month', new_category_path, class: 'btn btn-primary', style: 'align: center' %>

  </div>
</nav>

app/views/categories/new.html.erb
<nav class="navbar navbar-inverse">
  <h1 align="center" style="color: #BBBBBB; font-family: 'Bitstream Vera Sans'"> Bugeting</h1>
</nav>
<h2 style="font-family: 'cursive' ">New Category</h2>

<%= render 'form' %>


<nav class="navbar navbar-inverse navbar-fixed-bottom" style="align-self: center"
>
  <div class="container">

    <p class="navbar-text">
      <%= link_to 'Back', categories_path, class: 'btn btn-primary', style: 'align: center' %>
      <%= link_to 'Home', categories_path, class: 'btn btn-primary', style: 'align: center' %></p>

  </div>
</nav>

app/views/categories/show.html.erb
<nav class="navbar navbar-inverse">
 <h1 align="center" style="color: #BBBBBB; font-family: 'Bitstream Vera Sans'"> Bugeting</h1>
<br />

</nav>
<p id="notice"><%= notice %></p>
<div class="col-md-6 col-md-offset-3">
<p>
  <h3 style="font-family: Monaco; font-size: large">Month:
  <%= @category.name %></h3>
</p>

<p>
  <h3 style="font-family: Monaco; font-size: large">Year:
  <%= @category.type %></h3>
</p>
<p>
  <h3 style="font-family: Monaco; font-size: large">Current Budget
  <br /></h3>
  <strong>Total Income:</strong> <%= number_to_currency(@totalrevenue) %>
  <br />
  <strong>Total Costs:</strong> <%= number_to_currency(@totalcost) %>
  <br />
  <strong>Remaining Balance: </strong><%= number_to_currency(@balance) %>
</p>
<div class ="well">
  <%= form_for([@category, Revenue.new]) do |f| %>
    <p style="font-family: Monaco; font-size: medium"><%= f.label :name, "New Revenue" %><br/>
      <%= f.text_field :name %> <br />
      <%= f.label :name, "Amount" %><br/>
      <%= f.text_field :amount %>
    </p>

    <p style="font-family: Monaco; font-size: medium"><%= f.submit "Add Income", class:'btn btn-success' %></p>
<% end %>
<%= form_for([@category, Cost.new]) do |c| %>
    <p style="font-family: Monaco; font-size: medium"><%= c.label :name, "New Cost" %><br/>
      <%= c.text_field :name %> <br />
      <%= c.label :name, "Amount" %><br/>
      <%= c.text_field :amount %>
    </p>

    <p style="font-family: Monaco; font-size: medium"><%= c.submit "Add Cost", class:'btn btn-danger' %></p>
<% end %>
</div>
  <br />


<table class="table table-hover table-responsive table-bordered">
  <tbody>
  <div id="revenues">
    <% @category.revenues.each do |revenue| %>
        <%= div_for revenue do %>

            <tr>
              <td>
               <h3 style="font-family: Monaco; font-size: medium">Income</h3>
                <strong style="font-family: Monaco; font-size: medium">Posted <%= time_ago_in_words(revenue.created_at) %></strong><br/>
               <div class="well">
                <%= h(revenue.name) %>:
                <%= h(number_to_currency(revenue.amount)) %>
                 <%= link_to 'Destroy', revenue, method: :delete, data: { confirm: 'Are you sure?' } %>

               </div>
              </td>
            </tr>

        <% end %>
    <% end %>
  </div>

    <tbody style="background: #eeeeee">
    <div id="cost">
      <% @category.costs.each do |cost| %>
          <%= div_for cost do %>

              <tr>
                <td>
                  <h3 style="font-family: Monaco; font-size: medium">Cost</h3>
                  <strong style="font-family: Monaco; font-size: medium">Posted <%= time_ago_in_words(cost.created_at) %></strong><br/>
                  <div class="well">
                  <%= h(cost.name) %>:
                  <%= h(number_to_currency(cost.amount)) %>
                    <%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %>

                  </div>

                </td>
              </tr>

          <% end %>
      <% end %>
    </div>

  </tbody>

</table>

<nav class="navbar navbar-inverse navbar-static-bottom" style="align-self: center"
>
  <div class="container">

    <p class="navbar-text">
      <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-default', style: 'align: center' %>
      <%= link_to 'Back', categories_path, class: 'btn btn-default', style: 'align: center' %>
      <%= link_to 'Home', categories_path, class: 'btn btn-default', style: 'align: center' %></p>

  </div>

</nav>
</div>